float *p00_a ( int prob, int m, int n );
float *p00_b ( int prob, int m );
int p00_m ( int prob );
int p00_n ( int prob );
int p00_prob_num ( );
float *p00_x ( int prob, int n );
float *p01_a ( int m, int n );
float *p01_b ( int m );
int p01_m ( );
int p01_n ( );
float *p01_x ( int n );
float *p02_a ( int m, int n );
float *p02_b ( int m );
int p02_m ( );
int p02_n ( );
float *p02_x ( int n );
float *p03_a ( int m, int n );
float *p03_b ( int m );
int p03_m ( );
int p03_n ( );
float *p03_x ( int n );
float *p04_a ( int m, int n );
float *p04_b ( int m );
int p04_m ( );
int p04_n ( );
float *p04_x ( int n );
float *p05_a ( int m, int n );
float *p05_b ( int m );
int p05_m ( );
int p05_n ( );
float *p05_x ( int n );
float *p06_a ( int m, int n );
float *p06_b ( int m );
int p06_m ( );
int p06_n ( );
float *p06_x ( int n );
